id: create_secret
learningObjectives:
- Managing an api key as a secret
hints:
- Use the license key generated in the configuration file you’ve just downloaded.
- You can also find the license key in the [New Relic platform](https://one.newrelic.com/api-keys), make sure to use a key with type `INGEST - LICENSE`
- For help with creating a secret, you can try this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables)
startFlow:
  do:
  - actionId: bot_message
    params:
      person: devops
      messages:
        - text: We will setup the agent in a moment, but first we need to make sure we can use the API Key without exposing it.
        - text: We will achieve that by storing the api key as a secret in the k8s cluster.
        - text: You can use the following command to do so - `kubectl create secret generic my-secret --from-literal=my_secret=my_value`
        - text: Let's call both the secret and the key `datadog-api-key` and set the value to the generated API Key.
        - text: :instruction[Tell me when you're done]
trigger:
  type: user_message
  params:
    person: devops
  flowNode:
    if:
      conditions:
        - conditionId: is_user_message_text_ready_to_continue
      then:
        if:
          conditions:
            - conditionId: k8s_secret_defined
              name: datadog_api_key_config
              params:
                secretName: datadog-api-key
          then:
            if:
              conditions:
                - conditionId: text_match_regex
                  params:
                    text: ${outputs.datadog_api_key_config.value['datadog-api-key']}
                    regex: ^${user.integrations.datadog.api_key}$
              then:
                do:
                  - actionId: bot_message
                    params:
                      person: devops
                      messages:
                        - text: Great I see you've created the secret.
                  - actionId: finish_step
              else:
                do:
                  - actionId: bot_message
                    params:
                      person: devops
                      messages:
                        - text: The API key stored in the secret does not match the key you provided in the previous step.
          else:
            do:
            - actionId: bot_message
              params:
                person: devops
                messages:
                - text: Are you sure you've create a key named `datadog-api-key`?
                                    
      else:
        do:
          - actionId: bot_message
            params:
              person: devops
              messages:
                - text: Umm, If you need any help, just let me know that you’re stuck. If that’s not the case - take your time and tell me once you're ready :)