id: install_agent
learningObjectives:
- Installing the Datadog agent
hints:
- An environment variable can reference a secret by creating an environment variable with the `valueFrom` field that point to a `secretKeyRef` field. More info can be found in this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables)
startFlow:
  do:
  - actionId: bot_message
    params:
      person: devops
      messages:
      - text: We are ready to install the agent on the backend production server.
      - text: "Go ahead to `charts/templates/anythink-backend-deployment.yaml` and perform the following modifications:"
      - text: "- Add `DD_API_KEY` environment variable which should be a reference to the secret we've just created."
      - text: "- Add the agent installation command to the container args."
      - text: "Add the command before the start backend command:"      
      - text: |-
          ``` 
          spec:
            containers:
              - args:
                  - sh
                  - -c
                  - "DD_SITE=\"us5.datadoghq.com\" DD_HOSTNAME=anythink-backend bash -c \"$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh)\" & <existing_start_backend_command>"
      - text: Notice that the commands are seperated with `&` and not `&&` so that the agent will be installed in the background. Also, make sure to add the `DD_SITE` and `DD_HOST_NAME` variables to the command. Feel free to change the hostname as you wish.
      - text: Go ahead and open a PR with these changes.
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: devops
              messages:
              - text: Checking now
          - actionId: github_pr_comment
            params:
              person: devops
              message: Checking now.
        github_pr_workflow_complete_success:
          if:
            conditions:
            - conditionId: github_is_file_modified
              paramsFramework:
                node:
                  fileName: charts/templates/anythink-backend-deployment.yaml
              onFalseParams:
                pr_reject_message: Did you make sure you've added the environment variables and the installation command to the relevant deployment yml?
                pr_reject_message_name: file_not_modified
            - conditionId: github_does_file_contain
              equals: true
              params:
                regex: DD_API_KEY
                fileName: charts/templates/anythink-backend-deployment.yaml
              onFalseParams:
                pr_reject_message: It looks like you the environment variable `DD_API_KEY` is missing in your deployment yaml
                pr_reject_message_name: missing_api_key_env_var
            - conditionId: github_does_file_contain
              equals: true
              params:
                regex: secretKeyRef
                fileName: charts/templates/anythink-backend-deployment.yaml
              onFalseParams:
                pr_reject_message: Did you make sure the `DD_API_KEY` environment variable is referencing a key named `datadog-api-key`
                pr_reject_message_name: missing_secret_reference
            - conditionId: github_does_file_contain
              equals: true
              params:
                regex: "install_script_agent7"
                fileName: charts/templates/anythink-backend-deployment.yaml
              onFalseParams:
                pr_reject_message: It looks like the agent installation command is missing in your deployment yaml
                pr_reject_message_name: missing_agent_installation
            then:
              do:
              - actionId: bot_message
                params:
                  person: devops
                  messages:
                  - text: Looking good! You can merge the PR now.
              - actionId: github_pr_approve
                params:
                  person: devops
                  message: Looking good! You can merge the PR now.
            else:
              do:
              - actionId: bot_message
                params:
                  person: devops
                  messages:
                  - text: ${pr_reject_message}
              - actionId: github_pr_reject
                params:
                  person: devops
                  message: ${pr_reject_message}
                  messageName: ${pr_reject_message_name}

        github_pr_merged:
          do:
          - actionId: bot_message
            params:
              person: devops
              messages:
                - text: Great, your app will be soon deployed and the agent will start monitoring your host! It might take up to ten minutes and you could see your host appear in the [hosts dashboard](https://us5.datadoghq.com/dashboard/lists/preset/2)
          - actionId: finish_step
